//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace FreeYun.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FreeYun.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 接口弃用-请更新：-1000
        ///该服务已经停止：-1001
        ///软件尚未初始化：-1
        ///网络异常：-106
        ///封包错误：-107
        ///初始化-软件不存在或密钥错误：1001
        ///初始化-版本不存在：1002
        ///初始化-初始化成功：1003
        ///注册-软件已关闭注册：1043
        ///注册-用户名已存在：1004
        ///注册-机器码已经存在：1005
        ///注册-账号注册成功：1006
        ///登陆-软件已关闭验证：1007
        ///登陆-用户不存在：1008
        ///登陆-密码有误：1009
        ///登陆-机器码有误：1010
        ///登陆-账号过期：1011
        ///登陆-账号点数不足：1012
        ///登陆-验证人数已经上限：1013
        ///登陆-登陆成功：1014
        ///登陆-账号被锁定：1040
        ///用户信息-登陆过期：1015
        ///用户信息-用户已被删除：1016
        ///用户信息-查询成功：1017
        ///远程变量-登陆过期：1015
        ///远程变量-变量不存在：1018
        ///远程变量-获取成功：1019
        ///远程js-登陆过期：1015
        ///远程js-代码不存在：1020
        ///远程js-调用失败：1021
        ///远程js-调用成功：1022
        ///远程js-调用已达上限：1044
        ///留言反馈-软件不 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string freeyunError {
            get {
                return ResourceManager.GetString("freeyunError", resourceCulture);
            }
        }
    }
}
